"""Public, hardware-independent vehicle domain API."""

from .commands import (
    MAX_PERCENT,
    MAX_SEQUENCE,
    MIN_PERCENT,
    MIN_SEQUENCE,
    CommandPriority,
    CommandType,
    CommandValidationError,
    ControlCommand,
    DecodedCommand,
    ProtocolCodec,
    ProtocolContract,
    ProtocolError,
    ProtocolResponse,
    ResponseKind,
    crc16_ccitt,
)
from .safety import (
    InvalidTransition,
    SafetyDecision,
    SafetyError,
    SafetyPolicy,
    SafetyPrerequisiteError,
    SafetyStateMachine,
    resolve_command_queue,
)
from .state import (
    ControlMode,
    ControlState,
    DeviceConnection,
    DeviceKind,
    DeviceStatus,
    Fault,
    FaultCode,
    SafetyPhase,
)

__all__ = [
    "MAX_PERCENT",
    "MAX_SEQUENCE",
    "MIN_PERCENT",
    "MIN_SEQUENCE",
    "CommandPriority",
    "CommandType",
    "CommandValidationError",
    "ControlCommand",
    "ControlMode",
    "ControlState",
    "DecodedCommand",
    "DeviceConnection",
    "DeviceKind",
    "DeviceStatus",
    "Fault",
    "FaultCode",
    "InvalidTransition",
    "ProtocolCodec",
    "ProtocolContract",
    "ProtocolError",
    "ProtocolResponse",
    "ResponseKind",
    "SafetyDecision",
    "SafetyError",
    "SafetyPhase",
    "SafetyPolicy",
    "SafetyPrerequisiteError",
    "SafetyStateMachine",
    "crc16_ccitt",
    "resolve_command_queue",
]
